"""use database-generated IDs for questions and papers

Revision ID: 20260511_0005
Revises: 20260511_0004
Create Date: 2026-05-11 00:05:00.000000
"""

from collections.abc import Sequence

from alembic import op


revision: str = "20260511_0005"
down_revision: str | None = "20260511_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    for table_name in ("questions", "papers"):
        op.execute(
            f"""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = current_schema()
                      AND table_name = '{table_name}'
                      AND column_name = 'id'
                      AND is_identity = 'YES'
                ) THEN
                    ALTER TABLE {table_name}
                    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
                END IF;
            END $$;
            """
        )
        op.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence('{table_name}', 'id'),
                COALESCE((SELECT MAX(id) FROM {table_name}), 0) + 1,
                false
            );
            """
        )


def downgrade() -> None:
    for table_name in ("papers", "questions"):
        op.execute(
            f"""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = current_schema()
                      AND table_name = '{table_name}'
                      AND column_name = 'id'
                      AND is_identity = 'YES'
                ) THEN
                    ALTER TABLE {table_name} ALTER COLUMN id DROP IDENTITY IF EXISTS;
                END IF;
            END $$;
            """
        )
